### ISSUE TITLE
Headers are ignored

### ISSUE THREAD

**Issue by ilya-levin-lokalise** [ahivert/curl2ab#60]
Headers are ignored, even though `ab` tool seems to be supporting it.
Curl:
```
curl --location --request GET 'https://example.com/' \
--header 'X-Api-Token: aaabbbccc1234'
```

Flag that should've been added in `ab`:
> -H custom-header
Append extra headers to the request. The argument is typically in the form of a valid header line, containing a colon-separated field-value pair (i.e., "Accept-Encoding: zip/zop;8bit").

**Comment by ahivert** [comment]
Header as copied but only some are copied. The headers selected can be found here https://github.com/ahivert/curl2ab/blob/master/src/App.svelte#L9

**Comment by ahivert** [comment]
Updated list of accepted headers, should be ok now 
thanks to let me know :)

**Comment by ilya-levin-lokalise** [comment]
@ahivert thanks for the clarification! What is the idea behind filtering headers?

**Comment by ahivert** [comment]
just wanted to take only what was mandatory and avoid dealing with side effect I could encounter. But you are right it should not be so hard to deal with all headers
