### ISSUE TITLE
support headers

### ISSUE THREAD

**Issue by Pranav2612000** [ahivert/curl2ab#97]

**Comment by ahivert** [comment]
Can you be more specific on headers you need ?

There is currently all of these headers that are copied:
```
    "origin",
    "authorization",
    "accept",
    "cookie",
    "user-agent",
    "accept-encoding",
    "accept-language",
    "upgrade-insecure-requests",
    "x-api-token"
```

**Comment by saitanay** [comment]
This should be dynamic and iterative. And not limited to a set of predefined headers. 

A sample curl could look like this

`curl --location --request POST 'https://abc.net/webhook/abc' \
--header 'accept: application/json' \
--header 'api-key-header: aa@1234' \
--header 'Content-Type: application/json' \
--header 'testbytanay: thisisasamplekey' \
--data-raw '{
  "firstname": "Tanay",
  "lastname": "Sai",
  "phone" : "xxxx",
  "email": "xxx@gmail.com"
}'`

It should be able to translate the above into the required ab command. Same applies to data-raw.  (Someone has logged a separatte issue for data-raw. 

Without these 2 capabilities, this tool has not much of value

**Comment by ahivert** [comment]
all headers are now copied from curl to ab (already deployed). For data-raw, it's a bit more complex, as `ab` require creating a file containing the data to send. To keep simple command, ab must be replaced with another tool like [hey](https://github.com/rakyll/hey)
